# Copyright 2015 47Lining LLC.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
role_specification:
  - role_name: NucleatorBucketandqProvisioner
    trust_policy:
      Version : "2008-10-17"
      Statement :
        - Effect : Allow
          Sid : NucleatorBucketandqProvisionerTrustPolicy
          Principal :
            AWS : "arn:aws:iam::{{ aws_accounts[cage_names['build']['account']]['account_number'] }}:role/NucleatorAgent"
          Action : sts:AssumeRole
    access_policies:
      - policy_name: NucleatorBucketandqProvisionerAccessPolicy
        policy_document:
          Statement :
            - Effect: Allow
              Action: 
                - "cloudformation:CreateStack"
                - "cloudformation:UpdateStack"
                - "cloudformation:DescribeStacks"
                - "cloudformation:DescribeStackEvents"
                - "cloudformation:DescribeStackResource"
                - "cloudformation:GetTemplate"
              Resource: arn:aws:cloudformation:*
            - Effect: Allow
              Action: 
                - "s3:ListBucket"
                - "s3:GetObject"
                - "s3:CreateBucket"
                - "s3:PutObject"
                - "s3:GetBucketPolicy"
                - "s3:PutObjectAcl"
                - "s3:GetObjectAcl"
                - "s3:PutBucketPolicy"
                - "s3:DeleteObject"
                - "s3:PutBucketNotification"
                - "s3:PutBucketLogging"
              Resource: arn:aws:s3:::*
            - Effect: Allow
              Action: 
                - "iam:CreateInstanceProfile"
                - "iam:AddRoleToInstanceProfile"
                - "iam:RemoveRoleFromInstanceProfile"
                - "iam:DeleteInstanceProfile"
                - "iam:PassRole"
                - "iam:CreateRole"
                - "iam:PutRolePolicy"
              Resource: '*'
            - Effect: Allow
              Action:
                - "sqs:CreateQueue"
                - "sqs:SendMessage"
                - "sqs:ReadMessage"
                - "sqs:GetQueueAttributes"
                - "sqs:SetQueueAttributes"
              Resource: arn:aws:sqs:*
            - Effect: Allow
              Action:
                - "route53:ListHostedZones"
                - "route53:GetHostedZone"
                - "route53:ChangeResourceRecordSets"
              Resource: '*'
            - Effect: Allow
              Action:
                - "dynamodb:DescribeTable"
                - "dynamodb:CreateTable"
              Resource: '*'
  - role_name: NucleatorPipelineProvisioner
    trust_policy:
      Version : "2008-10-17"
      Statement :
        - Effect : Allow
          Sid : NucleatorPipelineProvisionerTrustPolicy
          Principal :
            AWS : "arn:aws:iam::{{ aws_accounts[cage_names['build']['account']]['account_number'] }}:role/NucleatorAgent"
          Action : sts:AssumeRole
    access_policies:
      - policy_name: NucleatorPipelineProvisionerAccessPolicy
        policy_document:
          Statement :
            - Effect: Allow
              Action: 
                - "iam:CreateInstanceProfile"
                - "iam:GetInstanceProfile"
                - "iam:AddRoleToInstanceProfile"
                - "iam:RemoveRoleFromInstanceProfile"
                - "iam:DeleteInstanceProfile"
                - "iam:PassRole"
              Resource: '*'
            - Effect: Allow
              Action: 
                - "datapipeline:CreatePipeline"
                - "datapipeline:PutPipelineDefinition"
                - "datapipeline:ActivatePipeline"
              Resource: '*'
  - role_name: NucleatorPipelineDefaultRole
    trust_policy:
      Version : "2008-10-17"
      Statement :
        - Effect : Allow
          Sid : NucleatorPipelineDefaultRoleTrustPolicy
          Principal :
            Service : 
              - "elasticmapreduce.amazonaws.com"
              - "datapipeline.amazonaws.com"
          Action : sts:AssumeRole
    access_policies:
      - policy_name: NucleatorPipelineDefaultRoleAccessPolicy
        policy_document:
          Statement :
            - Effect: Allow
              Action: 
                - "s3:List*"
                - "s3:Put*"
                - "s3:Get*"
                - "s3:DeleteObject"
                - "s3:CreateBucket"
                - "dynamodb:DescribeTable"
                - "dynamodb:Scan"
                - "dynamodb:Query"
                - "dynamodb:GetItem"
                - "dynamodb:BatchGetItem"
                - "dynamodb:UpdateTable"
                - "ec2:AuthorizeSecurityGroupIngress"
                - "ec2:DeleteTags"
                - "ec2:Describe*"
                - "ec2:CancelSpotInstanceRequests"
                - "ec2:CreateSecurityGroup"
                - "ec2:DeleteTags"
                - "ec2:CreateTags"
                - "ec2:ModifyImageAttribute"
                - "ec2:ModifyInstanceAttribute"
                - "ec2:RequestSpotInstances"
                - "ec2:RunInstances"
                - "ec2:StartInstances"
                - "ec2:StopInstances"
                - "ec2:TerminateInstances"
                - "elasticmapreduce:*"
                - "rds:DescribeDBInstances"
                - "rds:DescribeDBSecurityGroups"
                - "redshift:DescribeClusters"
                - "redshift:DescribeClusterSecurityGroups"
                - "sdb:BatchPutAttributes"
                - "sdb:Select*"
                - "sns:GetTopicAttributes"
                - "sns:ListTopics"
                - "sns:Publish"
                - "sns:Subscribe"
                - "sns:Unsubscribe"
                - "iam:PassRole"
                - "iam:ListRolePolicies"
                - "iam:GetRole"
                - "iam:GetRolePolicy"
                - "iam:ListInstanceProfiles"
                - "cloudwatch:*"
                - "datapipeline:DescribeObjects"
                - "datapipeline:EvaluateExpression"
              Resource: '*'
  - role_name: NucleatorPipelineDefaultResourceRole
    trust_policy:
      Version : "2008-10-17"
      Statement :
        - Effect : Allow
          Sid : NucleatorPipelineDefaultResourceRoleTrustPolicy
          Principal :
            Service: 
              - "ec2.amazonaws.com"
          Action : sts:AssumeRole
    access_policies:
      - policy_name: NucleatorPipelineDefaultResourceRoleAccessPolicy
        policy_document:
          Statement :
            - Effect: Allow
              Action: 
                - "s3:*"
                - "dynamodb:*"
                - "ec2:Describe*"
                - "elasticmapreduce:Describe*"
                - "elasticmapreduce:ListInstance*"
                - "elasticmapreduce:AddJobFlowSteps"
                - "rds:Describe*"
                - "datapipeline:*"
                - "cloudwatch:*"
                - "redshift:DescribeClusters"
                - "redshift:DescribeClusterSecurityGroups"
                - "sdb:*"
                - "sns:*"
                - "sqs:*"
              Resource: '*'
  - role_name: NucleatorBucketandqOrchestrator
    trust_policy:
      Version : "2008-10-17"
      Statement :
        - Effect : Allow
          Sid : NucleatorBucketandqOrchestratorTrustPolicy
          Principal :
            AWS : "arn:aws:iam::{{ aws_accounts[cage_names['build']['account']]['account_number'] }}:role/NucleatorAgent"
          Action : sts:AssumeRole
    access_policies:
      - policy_name: NucleatorBucketandqOrchestratorAccessPolicy
        policy_document:
          Statement :
            - Effect: Allow
              Action:
                - "sqs:GetQueueUrl"
                - "sqs:SendMessage"
              Resource: arn:aws:sqs:*